### ISSUE TITLE
development status

### ISSUE THREAD

**Issue by fthamura** [cloudfoundry-attic/uaa-keystone#1]
any status and what kind of development environment that we should prepare to join this work?

so we can test and know the future and may be test the code of this project?

i am interest with OAuth2 related work anyway.

**Comment by fhanik** [comment]
There is a simple authentication manager in the UAA (there is on in the login server too, but that one is being deprecated)
https://github.com/cloudfoundry/uaa/blob/develop/common/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/KeystoneAuthenticationManager.java#L27-27

Development will continue here in the UAA project. The next step is to enable selecting a domain during authentication against Keystone v3. Story is here: https://www.pivotaltracker.com/story/show/72468712

testing is easy, one just specifies keystone as a profile. for example, -Dspring.profiles.active=keystone,default

You can see a keystone profile being used here:
https://travis-ci.org/cloudfoundry/uaa/builds/26410001
